CREATE DATABASE SGL;
    USE SGL;

CREATE TABLE PEDIDOS (
    ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
    ID_FUNCIONARIO INT NOT NULL,
    ID_LANCHE INT,
    ID_BEBIDA INT,
    DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIOS(ID_FUNCIONARIO),
    FOREIGN KEY (ID_LANCHE) REFERENCES LANCHES(ID_LANCHE),
    FOREIGN KEY (ID_BEBIDA) REFERENCES BEBIDAS(ID_BEBIDA)
);

CREATE TABLE FUNCIONARIOS (
    ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CARGO VARCHAR(50),
    TELEFONE VARCHAR(20)
);

CREATE TABLE LANCHES (
    ID_LANCHE INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT,
    PRECO DECIMAL(10,2) NOT NULL
);

CREATE TABLE BEBIDAS (
    ID_BEBIDA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TAMANHO VARCHAR(50),
    PRECO DECIMAL(10,2) NOT NULL
);